### ISSUE TITLE
Documentation: how to set AWS configuration variables?

### ISSUE THREAD

**Issue by gburgett** [heroku/heroku-buildpack-awscli#11]
Howdy!

For my application, I need to download an s3 bucket to a local folder whenever the dyno restarts (which resets my ephemeral file system).  This currently takes ~ 4 min.

I'd like to set some configuration parameters to try to speed this up.  How should I go about configuring this?
```
aws configure set default.s3.max_concurrent_requests 1000
aws configure set default.s3.max_queue_size 100000
```

Should I run these during the Heroku build phase?  Will they be added to the slug?  Or should I set them every time before I run `aws s3 sync`?

**Comment by dmathieu** [comment]
This isn't something this buildpack deals with. All it does is download the awscli binary and put it in the path.

I don't know where AWS stores config. But if that's within your project (`/app`), you can do it at build time, it will be kept at runtime.
If it's stored in the global path (somewhere within `~`), you need to run it when your app starts.

In any case, this buildpack is meant to be quite minimalistic, and only to setup the CLI binary. So I'm going to close this issue.

**Comment by gburgett** [comment]
Once I figure this out, would you mind if I send a Pull Request to add that info to the readme?

**Comment by dmathieu** [comment]
Sure.
