### ISSUE TITLE
Recent changes cause build error: "/bin/sh: 1: aws: not found" (AWS CLI binary has moved)

### ISSUE THREAD

**Issue by paulchaplin** [heroku/heroku-buildpack-awscli#4]
First: Thanks for providing this buildpack; it's very useful!

We were successfully using this via `heroku-community/awscli` (which [resolves to here](https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/awscli.tgz)), but the recent changes on `master` caused the following error:

`/bin/sh: 1: aws: not found`

The only other buildpacks we use are `heroku/nodejs` and `heroku/ruby`.

It looks like the AWS CLI binary is now placed in a different location by this buildpack, and that our fairly simple setup chokes on that.

Should we be **doing something differently?**

We have this as a workaround for now:

1. In the application settings, remove the existing `heroku-community/awscli` buildpack.
2. Add a new buildpack referencing the specific commit for the last working version, using `https://github.com/heroku/heroku-buildpack-awscli.git#01f21a8ac4a3964b0a0475444e0716ec37109256` as the buildpack name.

This seems to successfully overload the "You can optionally specify a tag or a branch ..." functionality [described here](https://devcenter.heroku.com/articles/buildpacks#using-a-third-party-buildpack), but is obviously not a long-term fix.

**Comment by dmathieu** [comment]
Please try again. I shipped #3 15 minutes ago, and it fixes this :)

**Comment by paulchaplin** [comment]
Thanks! I'll try again as soon as the current Heroku maintenance is finished, and will edit this comment if all is okay, and post a new one if for some reason I still encounter the issue. Really appreciate your effort.

*Edit:* It indeed works again. :)
