### ISSUE TITLE
Installation not working in Heroku CI

### ISSUE THREAD

**Issue by chrblabla** [heroku/heroku-buildpack-awscli#5]
Hi there!

I tried using the buildpack in the Heroku CI and it failed installing with the following messages:

```
-----> Fetching heroku-community/awscli buildpack...
       buildpack downloaded
-----> AWS CLI app detected
-----> Installing AWS CLI
       /tmp/buildpacks/737ef5e961c7064fa7fd8cc69b95612443dcbec3b4f9832c1b4849dd69f3156dc19a15b3b06af89a6aff0ccee7d9df74d241d01980c5ca6d440c8dbec62b779b/bin/compile: line 34: /app/.awscli/awscli-bundle/install: No such file or directory
```

It appears to me that the build, app and tmp directories have a slightly different setup in the Heroku CI than in the slug itself which leads to the deletion of the freshly unzipped folder.

**Comment by dmathieu** [comment]
Thank you for fixing this in #6.
