### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by jaxgeller** [heroku/heroku-buildpack-awscli#7]
Where is the aws binary installed to? Having trouble getting the command to work.

I have the buildpack in index=1, with ruby and node as well. Have tried `aws` and `/app/.awscli/bin/aws`

**Comment by jaxgeller** [comment]
-----> AWS CLI app detected
-----> Installing AWS CLI
       Running cmd: /usr/bin/python virtualenv.py --no-download --python /usr/bin/python /app/.awscli
       Running cmd: /app/.awscli/bin/pip install --no-cache-dir --no-index --find-links file:///tmp/build_a501fc09e09cc119033cc8fa4003c379/.awscli/awscli-bundle/packages/setup setuptools_scm-1.15.7.tar.gz
       Running cmd: /app/.awscli/bin/pip install --no-cache-dir --no-index --find-links file:///tmp/build_a501fc09e09cc119033cc8fa4003c379/.awscli/awscli-bundle/packages awscli-1.16.169.tar.gz
       You can now run: /app/.awscli/bin/aws --version
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_OPTIONS=--max-old-space-size=2560
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 10.x...
       Downloading and installing node 10.16.0...
       Using default npm version: 6.9.0
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.16.0)...
       Installed yarn 1.16.0
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.16.0
       <REDACTED>
       
-----> Build
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       yarn install v1.16.0
       [1/4] Resolving packages...
       [2/4] Fetching packages...
      <REDACTED>
       [4/4] Building fresh packages...
       warning Ignored scripts due to flag.
       Done in 8.49s.
       
-----> Build succeeded!
 !     Unmet dependencies don't fail yarn install but may cause runtime issues
       https://github.com/npm/npm/issues/7494
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.5.0
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/............
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       <REDACTED>
       Bundle complete! 67 Gemfile dependencies, 132 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (5.66s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Removing bcrypt (3.1.12)
       The latest bundler is 2.0.1, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.16.0
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.7: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-react > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-react > @babel/plugin-transform-react-jsx@7.3.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-react > @babel/plugin-transform-react-jsx-self@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-react > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning " > @babel/preset-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-typescript > @babel/plugin-transform-typescript@7.4.5" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
       warning " > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
       warning " > react-sortable-tree@2.6.0" has unmet peer dependency "react-dnd@^6.0.0 || ^7.0.0".
       warning " > babel-jest@24.8.0" has unmet peer dependency "@babel/core@^7.0.0".
       warning "babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
       warning " > webpack-dev-server@3.4.1" has unmet peer dependency "webpack@^4.0.0".
       warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
       [4/4] Building fresh packages...
       Done in 40.30s.
       Compiling…
       Compiled all packs in /tmp/build_a501fc09e09cc119033cc8fa4003c379/public/packs
       Uploading assets to s3
       /app/.awscli/bin/aws s3 sync public/ s3://BUCKETHERE
       sh: 1: /app/.awscli/bin/aws: not found
       D, [2019-06-03T18:11:40.031647 #3063] DEBUG -- : Command failed with status (127): [/app/.awscli/bin/aws s3 sync public/ s3://...] excluded from capture: DSN not set
       rake aborted!
       Command failed with status (127): [/app/.awscli/bin/aws s3 sync public/ s3://...]
       /tmp/build_a501fc09e09cc119033cc8fa4003c379/lib/tasks/after_assets_precompile.rake:4:in `block in <top (required)>'
       /tmp/build_a501fc09e09cc119033cc8fa4003c379/lib/tasks/after_assets_precompile.rake:11:in `block in <top (required)>'
       /tmp/build_a501fc09e09cc119033cc8fa4003c379/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
       Tasks: TOP => after_assets_precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by guzart** [comment]
I am experiencing the same issue when trying to use the aws cli from a command that's executed by subsequent buildpack.

I did an `ls ~/.awscli` and the directory is empty. 🤷‍♂

**Comment by jaxgeller** [comment]
@guzart We fixed this by adding the python buildpack and a requirements.txt

```
# requirements.txt
awscli==1.16.169
tox>=2.3.1,<3.0.0
docutils>=0.10
# botocore and the awscli packages are typically developed
# in tandem, so we're requiring the latest develop
# branch of botocore when working on the awscli.
-e git://github.com/boto/botocore.git@develop#egg=botocore
-e git://github.com/boto/s3transfer.git@develop#egg=s3transfer
-e git://github.com/boto/jmespath.git@develop#egg=jmespath
nose==1.3.7
colorama>=0.2.5,<=0.3.9
mock==1.3.0
rsa>=3.1.2,<=3.5.0
wheel==0.24.0
PyYAML>=3.10,<=3.13
```

**Comment by guzart** [comment]
Oh nice! I didn't know anything about requirements.txt. Granted, I don't know anything about python. 😅 

Thanks for sharing your solution, I solved it by manually installing it. 
```
  curl --silent --show-error -o /tmp/awscli-bundle.zip "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
  unzip -qq -d /tmp /tmp/awscli-bundle.zip
  /tmp/awscli-bundle/install -i ~/.awscli
  rm -rf /tmp/awscli*
```
