### ISSUE TITLE
Should groff be added as a dependency?

### ISSUE THREAD

**Issue by nettum** [heroku/heroku-buildpack-awscli#8]
Running commands on a one-off dyno with this buildback works nicely:
```
~ $ aws --version
aws-cli/1.16.208 Python/2.7.15rc1 Linux/4.4.0-1048-aws botocore/1.12.198
```

But if I try to run `aws help` I get the following error:
```
~ $ aws help     

Could not find executable named "groff"
```
Should groff/less be added as a dependency for this buildback or should this be fixed by aws?  
Related aws-cli issue: https://github.com/aws/aws-cli/issues/1957

**Comment by dmathieu** [comment]
All this buildpack does is install the CLI using the [bundled installation](https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html) provided by AWS.
It a dependency is missing from there, that's where it should be added.

**Comment by nettum** [comment]
:+1: makes sense.

**Comment by AllanOricil** [comment]
I can't install aws cli on heroku because It is missing groff and less. I tried to use apt-get install for both missing dependencies but it did not work. How can I fix this issue?
